### PR TITLE
Some small updates to opam

### PR DESCRIPTION
**Pull request by rgrinberg**
@AltGr would be great to have a github 3.0 compatible release

### CODE REVIEW

**Comment by AltGr** [comment]
Thanks!

**Comment by rgrinberg** [comment]
As far as I can see, the change in constraints was done later in another commit. What about the change to use the github-unix package? github.unix only exists for compatibility.

**Comment by AltGr** [comment]
Ah, indeed! The rest has been merged manually in other commits, but that piece remains missing. Thanks.

**Comment by rgrinberg** [comment]
How come the last commit wasn't merged into master yet?

**Comment by rjbou** [comment]
PR superseded by #85 . Thanks @rgrinberg

**Pull request closed without merging**
